[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0\x41\x66ile:///home/cipherlogs/Documents/Screens/2026-08-30_22-25-26.mp4)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\a\x7f\0\0\x4\x37\0\0\0\0\0\0\0\x14\0\0\a\x7f\0\0\x4K\0\0\0\0\x2\0\0\0\a\x80\0\0\0\0\0\0\0\0\0\0\a\x7f\0\0\x4\x37)

[FullScreen]
pos=@Point(512 1013)
screen=@Rect(0 0 1920 1080)
wide=false

[MainWindow]
QtStyle=System's default
adv-controls=0
bgSize=@Size(960 1006)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[Mediainfo]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x3\xc0\0\0\0\0\0\0\a\x7f\0\0\x4\x37\0\0\x3\xc0\0\0\0\0\0\0\a\x7f\0\0\x4\x37\0\0\0\0\0\0\0\0\a\x80\0\0\x3\xc0\0\0\0\0\0\0\a\x7f\0\0\x4\x37)

[OpenDialog]
advanced=false
netMRL=https://iptv-org.github.io/iptv/categories/sports.m3u
size=@Size(526 423)

[Preferences]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x2\x34\0\0\0\xf2\0\0\x5W\0\0\x3\xc9\0\0\x2\x36\0\0\x1\f\0\0\x5U\0\0\x3\xc7\0\0\0\0\0\0\0\0\a\x80\0\0\x2\x36\0\0\x1\f\0\0\x5U\0\0\x3\xc7)

[RecentsMRL]
list=file:///home/cipherlogs/Documents/Screens/2026-08-30_22-25-26.mp4, file:///home/cipherlogs/Documents/Screens/2024-09-20_15-59-21.mp4, https://30a-tv.com/feeds/vidaa/golf.m3u8, https://iptv-org.github.io/iptv/categories/sports.m3u, http://143.244.62.109:80/as3slo/index.m3u8, https://nl1.nghk.ai/ArenaSport3HD/index.m3u8, https://nl1.nghk.ai/AS3HRHD/index.m3u8, https://nl1.nghk.ai/ArenaSport3BH/index.m3u8, https://nl1.nghk.ai/ArenaPremium2HD/index.m3u8, http://88.212.15.19/live/test_arenasport_dva/playlist.m3u8, https://lb.dstvmultimedia.com/AS2SLOHD/index.m3u8, https://nl1.nghk.ai/ArenaSport2HD/index.m3u8, https://nl1.nghk.ai/AS2HRHD/index.m3u8, https://nl1.nghk.ai/ArenaSport2BH/index.m3u8, http://xplatinmedia.com:8080/Elko/mhj8LHTJJC/53449, https://nl1.nghk.ai/ArenaPremium1HD/index.m3u8, http://88.212.15.19/live/test_arenasport/playlist.m3u8, https://lb.dstvmultimedia.com/AS1SLOHD/index.m3u8, https://nl1.nghk.ai/ArenaSport1HD/index.m3u8, https://nl1.nghk.ai/AS1HRHD/index.m3u8, https://nl1.nghk.ai/ArenaSport1BH/index.m3u8, https://nl1.nghk.ai/ArenaFight/index.m3u8, "https://hls.rundletv.eu.org/LIVE$AntenaSport/6.m3u8/Level/300720051?end=END&start=LIVE", https://liveeu-gcp.alkassdigital.net/alkass2-p/main.m3u8, https://liveeu-gcp.alkassdigital.net/alkass3-p/main.m3u8, https://liveeu-gcp.alkassdigital.net/alkass6-p/main.m3u8, https://liveeu-gcp.alkassdigital.net/shooflive2/main.m3u8, https://liveeu-gcp.alkassdigital.net/shooflive/main.m3u8, https://liveeu-gcp.alkassdigital.net/alkass7-p/main.m3u8, https://liveeu-gcp.alkassdigital.net/alkass1-p/main.m3u8
times=0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
